version: '2.1'
services:
  world_db:    
    image: world_db:latest
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    ports:
    - 5431:5432 # Адрес для доступа извне : внутренний
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 5
    container_name: world_db
  app:
    image: app:latest
    environment:
    - DB_USERNAME=postgres
    - DB_PASSWORD=postgres
    - DB_ADDRESS=world_db
    - DB_PORT=5432  # внутренний адрес контейнера базы (не внешний (справа))
    - DB_NAME=world
    - DB_SSL=disable
    - SERVER_PORT=:8080
    ports:
    - 8082:8080 # Адрес подключения : адрес передачи с сервера
    container_name: app

    depends_on:
      "world_db":
        condition: service_healthy